name: GitHub CI
on:
  push:
    tags:
      - "v*"
jobs:
  build_dmg:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 12.x
        uses: actions/setup-node@master
        with:
          node-version: 12.x
      - name: Install
        run: yarn install --frozen-lockfile --ignore-optional
      - name: Build
        run: yarn build:prod
      - name: Release
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          APP_BUNDLE_ID: ${{ secrets.APP_BUNDLE_ID }}
          ASC_PROVIDER: ${{ secrets.ASC_PROVIDER }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn release

  build_appx:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 12.x
        uses: actions/setup-node@master
        with:
          node-version: 12.x
      - name: Install
        run: yarn install --frozen-lockfile --ignore-optional
      - name: Build
        run: yarn build:prod
      - name: Release
        env:
          IDENTITY_NAME: ${{ secrets.IDENTITY_NAME }}
          PUBLISHER: ${{ secrets.PUBLISHER }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn release
